package com.aetins.customerportal.core.enums;

/**
 * Portal supported transactions
 * @author avinash
 *
 */
public enum TRANSACTIONS {

	UPDATEINFORMATION_TRANSACTION,
	REDIRECTION_TRANSACTION,
	SWITCHING_TRANSACTION,
	REDIRECTION_SWITCHING_TRANSACTION,
	PARTIALWITHDRAWAL_TRANSACTION,
	REINSTATEMENT_TRANSACTION,
	CLAIMINTIMATION_TRANSACTION,
	CONTRIBUTION_ALTERATION_TRANSACTION,
	PROTECTION_BENEFIT_TRANSACTION
}
